### PR TITLE
This will make the Auth errors stop

### PR DESCRIPTION
**Pull request by StyStatic**
Please

### CODE REVIEW

**Comment by cyoung06** [comment]
I wont consider this as a fix.

Just removing popup does not solve any problem

**Review by cyoung06 — CHANGES_REQUESTED** [review]
Just removing message does not fix anything.

Maybe add a close button or something like that.

**Comment by StyStatic** [comment]
Added a toggle in the Debug Menu
It isn't the prettiest but its the best i could do with my limited knowledge of your mod's structure

**Review by cyoung06 — CHANGES_REQUESTED** [review]
Loader is not supposed to access the Mod's config,
and the Mod is not supposed to access the Loader's config directly via file

Please add the option in the loader's config file or create dismiss button in the gui

**Comment by StyStatic** [comment]
If I added it to loader config would you want it to default to hidden auth errors or not hidden?

**Comment by StyStatic** [comment]
Closing to issue a pull request from a new branch

**Pull request closed without merging**
